<?php
declare(strict_types=1);
use Canteen\Reports\ReportFormatter as F;
?>
<div class="report-document">
<table class="identity" width="100%" cellpadding="0" cellspacing="0"><tr>
<td width="28%"><?php if ($report['logo']): ?><img src="<?= F::text($report['logo']['src']) ?>" width="<?= (int) $report['logo']['width'] ?>" height="<?= (int) $report['logo']['height'] ?>" alt="Concentrix Ghana"><?php endif; ?></td>
<td width="72%" align="right"><strong class="company">Concentrix Ghana</strong><br><span class="muted">Canteen Management System</span></td>
</tr></table>
<h1><?= F::text($report['title']) ?></h1>
<p class="period"><?= F::text($report['period_label']) ?></p>
<table class="metadata" width="100%" cellpadding="5" cellspacing="0">
<?php foreach ([
    ['Generated By', $report['generated_by'], 'User Role', $report['generated_by_role']],
    ['Report Ref', $report['reference'], 'Shift', $report['filters']['shift_type'] ?: 'All Shifts'],
] as $line): ?><tr><td width="16%" class="label"><?= F::text($line[0]) ?></td><td width="34%"><?= F::text($line[1]) ?></td><td width="16%" class="label"><?= F::text($line[2]) ?></td><td width="34%"><?= F::text($line[3]) ?></td></tr><?php endforeach; ?>
</table>
<h2>Report summary</h2>
<table class="kpis" width="100%" cellpadding="7" cellspacing="0"><tr>
<?php foreach ($report['summary'] as $label => $value): ?><td width="<?= 100 / max(1, count($report['summary'])) ?>%"><span class="muted"><?= F::text($label) ?></span><br><strong class="kpi-value"><?= F::text($value) ?></strong></td><?php endforeach; ?>
</tr></table>
<?php if (!array_filter($report['sections'], static fn(array $section): bool => count($section['rows']) > 0)): ?>
<p class="empty">No records were found for the selected report period and filters.</p>
<?php else: ?>
<?php foreach ($report['sections'] as $section): ?>
<table class="report-table" width="100%" cellpadding="6" cellspacing="0">
<colgroup><?php foreach ($section['columns'] as $i => $column): ?><col style="width:<?= count($section['columns']) === 3 ? [23, 59, 18][$i] : [82, 18][$i] ?>%"><?php endforeach; ?></colgroup>
<thead><tr><th class="section-heading" colspan="<?= count($section['columns']) ?>"><h2><?= F::text($section['title']) ?></h2></th></tr><tr><?php foreach ($section['columns'] as $i => $column): ?><th style="font-weight:bold; background-color:#e9eff1; color:#153f4b;" class="column-heading" scope="col" width="<?= count($section['columns']) === 3 ? [23, 59, 18][$i] : [82, 18][$i] ?>%" align="<?= $i === count($section['columns']) - 1 ? 'right' : 'left' ?>"><?= F::text($column) ?></th><?php endforeach; ?></tr></thead>
<tbody>
<?php if (!$section['rows']): ?><tr><td colspan="<?= count($section['columns']) ?>" class="empty">No records were found for the selected report period and filters.</td></tr><?php endif; ?>
<?php foreach ($section['rows'] as $row): ?><tr><?php foreach ($row as $i => $cell): ?><td class="report-cell" width="<?= count($row) === 3 ? [23, 59, 18][$i] : [82, 18][$i] ?>%" align="<?= $i === count($row) - 1 ? 'right' : 'left' ?>"><?= F::text($cell) ?></td><?php endforeach; ?></tr><?php endforeach; ?>
<tr class="total"><td colspan="<?= count($section['columns']) - 1 ?>">Total<?= str_contains($section['title'], 'up to 10') ? ' (listed ranking)' : '' ?></td><td align="right"><?= number_format($section['total']) ?></td></tr>
</tbody></table>
<?php endforeach; ?>
<?php endif; ?>
</div>
